name: CI / Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      # Install dependencies
      - run: npm ci

      # Lint & Prettier check
      - name: Lint & Prettier
        run: |
          npm run lint
          npx prettier --check "**/*.{ts,vue,js,json,css,scss,md}"

      # Run tests
      - name: Run Tests
        run: npm test

      # Build Vite project
      - name: Build Project
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
